export type Scheme = 'light' | 'dark';

export interface Palette {
  scheme: Scheme;
  accent: string;
  accentLight: string;
  bgTop: string;
  bgMid: string;
  bgBottom: string;
  glassBg: string;
  glassBorder: string;
  textDark: string;
  textMid: string;
  textDim: string;
}

export interface Theme {
  id: string;
  name: string;
  light: Palette;
  dark: Palette;
}

const DARK_GLASS_BG = 'rgba(255,255,255,0.06)';
const DARK_GLASS_BORDER = 'rgba(255,255,255,0.12)';
const LIGHT_GLASS_BG = 'rgba(255,255,255,0.55)';
const LIGHT_GLASS_BORDER = 'rgba(255,255,255,0.85)';

export const THEMES: Theme[] = [
  {
    id: 'sage-garden',
    name: 'Sage Garden',
    light: {
      scheme: 'light',
      accent: '#2D6A4F',
      accentLight: '#E8F5EE',
      bgTop: '#D4E8D4',
      bgMid: '#F7F3ED',
      bgBottom: '#E8F0E8',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1A1A2E',
      textMid: '#4A5568',
      textDim: '#9AA5B4',
    },
    dark: {
      scheme: 'dark',
      accent: '#6FBF8F',
      accentLight: 'rgba(111,191,143,0.18)',
      bgTop: '#0D1B14',
      bgMid: '#14241B',
      bgBottom: '#0A1410',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#E8F0EC',
      textMid: '#B0BFB7',
      textDim: '#6E7C75',
    },
  },
  {
    id: 'khidir-kasbah',
    name: 'Khidir Kasbah',
    light: {
      scheme: 'light',
      accent: '#B8602A',
      accentLight: '#FBEFE3',
      bgTop: '#FBE5CE',
      bgMid: '#FFF7EE',
      bgBottom: '#F8E8D4',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2A1A10',
      textMid: '#6E4F3B',
      textDim: '#B49680',
    },
    dark: {
      scheme: 'dark',
      accent: '#F0A26A',
      accentLight: 'rgba(240,162,106,0.18)',
      bgTop: '#1F1208',
      bgMid: '#2B1A0E',
      bgBottom: '#170D06',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FBEFE3',
      textMid: '#C9B5A2',
      textDim: '#7C6A58',
    },
  },
  {
    id: 'midnight-mihrab',
    name: 'Midnight Mihrab',
    light: {
      scheme: 'light',
      accent: '#2C3E70',
      accentLight: '#E5EBF5',
      bgTop: '#DDE7F3',
      bgMid: '#F4F6FA',
      bgBottom: '#E2E9F1',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#14213D',
      textMid: '#4A5C7A',
      textDim: '#8E99B0',
    },
    dark: {
      scheme: 'dark',
      accent: '#7BA3E8',
      accentLight: 'rgba(123,163,232,0.18)',
      bgTop: '#08111F',
      bgMid: '#101A2E',
      bgBottom: '#060C18',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#E8EEF8',
      textMid: '#B0BBD1',
      textDim: '#6E7790',
    },
  },
  {
    id: 'jade-mosque',
    name: 'Jade Mosque',
    light: {
      scheme: 'light',
      accent: '#0F8F87',
      accentLight: '#DEF2F0',
      bgTop: '#C9E8E5',
      bgMid: '#F1FAF8',
      bgBottom: '#DCEEEC',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#0E2A28',
      textMid: '#3F6663',
      textDim: '#8AA3A1',
    },
    dark: {
      scheme: 'dark',
      accent: '#4FCFC4',
      accentLight: 'rgba(79,207,196,0.18)',
      bgTop: '#08161A',
      bgMid: '#102528',
      bgBottom: '#060F12',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#E0F4F2',
      textMid: '#A4C0BE',
      textDim: '#66807E',
    },
  },
  // ─── Remaining themes (sorted alphabetically by id) ────────────────────────
  {
    id: 'alhambra-red',
    name: 'Alhambra Red',
    light: {
      scheme: 'light',
      accent: '#8B2C2C',
      accentLight: '#FAE0E0',
      bgTop: '#F0CCCC',
      bgMid: '#FEF5F5',
      bgBottom: '#E8C0C0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2A0808',
      textMid: '#6E2828',
      textDim: '#B07878',
    },
    dark: {
      scheme: 'dark',
      accent: '#E06868',
      accentLight: 'rgba(224,104,104,0.18)',
      bgTop: '#1C0606',
      bgMid: '#280808',
      bgBottom: '#140404',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FAE0E0',
      textMid: '#C89090',
      textDim: '#784C4C',
    },
  },
  {
    id: 'almond-bloom',
    name: 'Almond Bloom',
    light: {
      scheme: 'light',
      accent: '#B07060',
      accentLight: '#FAEEE8',
      bgTop: '#F4D8C8',
      bgMid: '#FEF7F2',
      bgBottom: '#EDCFC0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2A1410',
      textMid: '#6E3E30',
      textDim: '#B0907C',
    },
    dark: {
      scheme: 'dark',
      accent: '#E8B098',
      accentLight: 'rgba(232,176,152,0.18)',
      bgTop: '#1C0E08',
      bgMid: '#281410',
      bgBottom: '#140804',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FAEEE8',
      textMid: '#C8A090',
      textDim: '#785848',
    },
  },
  {
    id: 'amber-musk',
    name: 'Saffron Sands',
    light: {
      scheme: 'light',
      accent: '#B8780A',
      accentLight: '#FDF2DC',
      bgTop: '#F8E8BC',
      bgMid: '#FFFBF0',
      bgBottom: '#F5E6C8',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#241600',
      textMid: '#6A4E00',
      textDim: '#B89C50',
    },
    dark: {
      scheme: 'dark',
      accent: '#F0B840',
      accentLight: 'rgba(240,184,64,0.18)',
      bgTop: '#1A1200',
      bgMid: '#261C04',
      bgBottom: '#120D00',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FDF2DC',
      textMid: '#C8B070',
      textDim: '#786840',
    },
  },
  {
    id: 'apricot-dawn',
    name: 'Apricot Dawn',
    light: {
      scheme: 'light',
      accent: '#C87830',
      accentLight: '#FCEBD8',
      bgTop: '#F8D8B0',
      bgMid: '#FFF7EE',
      bgBottom: '#F0CCA0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2A1808',
      textMid: '#6E3E18',
      textDim: '#B08858',
    },
    dark: {
      scheme: 'dark',
      accent: '#F0A878',
      accentLight: 'rgba(240,168,120,0.18)',
      bgTop: '#1C0E04',
      bgMid: '#281408',
      bgBottom: '#140804',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FCEBD8',
      textMid: '#C89878',
      textDim: '#785838',
    },
  },
  {
    id: 'aqua-dome',
    name: 'Aqua Dome',
    light: {
      scheme: 'light',
      accent: '#0A8FAA',
      accentLight: '#DCEEF5',
      bgTop: '#B4E4F0',
      bgMid: '#EFF9FC',
      bgBottom: '#C4ECF0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#0A2830',
      textMid: '#1A6070',
      textDim: '#6AABB8',
    },
    dark: {
      scheme: 'dark',
      accent: '#40C8D8',
      accentLight: 'rgba(64,200,216,0.18)',
      bgTop: '#061618',
      bgMid: '#0A2228',
      bgBottom: '#04100E',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#DCEEF5',
      textMid: '#80C0CE',
      textDim: '#407890',
    },
  },
  {
    id: 'asphalt-azaan',
    name: 'Asphalt Azaan',
    light: {
      scheme: 'light',
      accent: '#2A2A2A',
      accentLight: '#ECECEC',
      bgTop: '#E0E0E0',
      bgMid: '#F8F8F8',
      bgBottom: '#E8E8E8',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#0A0A0A',
      textMid: '#505050',
      textDim: '#A0A0A0',
    },
    dark: {
      scheme: 'dark',
      accent: '#D0D0D0',
      accentLight: 'rgba(208,208,208,0.15)',
      bgTop: '#0A0A0A',
      bgMid: '#141414',
      bgBottom: '#050505',
      glassBg: 'rgba(255,255,255,0.05)',
      glassBorder: 'rgba(255,255,255,0.10)',
      textDark: '#F0F0F0',
      textMid: '#A8A8A8',
      textDim: '#606060',
    },
  },
  {
    id: 'attar-rose',
    name: 'Attar Rose',
    light: {
      scheme: 'light',
      accent: '#A8345E',
      accentLight: '#FAE3EC',
      bgTop: '#F4CCD8',
      bgMid: '#FEF4F7',
      bgBottom: '#ECC0CE',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2A0810',
      textMid: '#702838',
      textDim: '#B07888',
    },
    dark: {
      scheme: 'dark',
      accent: '#E07090',
      accentLight: 'rgba(224,112,144,0.18)',
      bgTop: '#1E0810',
      bgMid: '#2A0E16',
      bgBottom: '#140408',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FAE3EC',
      textMid: '#C8889A',
      textDim: '#784858',
    },
  },
  {
    id: 'bedouin-tent',
    name: 'Bedouin Tent',
    light: {
      scheme: 'light',
      accent: '#5A3820',
      accentLight: '#F0E3D8',
      bgTop: '#E0CCB8',
      bgMid: '#FAF4ED',
      bgBottom: '#D8C0A8',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1A0C04',
      textMid: '#4A2C18',
      textDim: '#98785C',
    },
    dark: {
      scheme: 'dark',
      accent: '#C09070',
      accentLight: 'rgba(192,144,112,0.18)',
      bgTop: '#160C04',
      bgMid: '#221408',
      bgBottom: '#0C0604',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F0E3D8',
      textMid: '#C09078',
      textDim: '#785840',
    },
  },
  {
    id: 'berry-dusk',
    name: 'Berry Dusk',
    light: {
      scheme: 'light',
      accent: '#7A2060',
      accentLight: '#F0E0EC',
      bgTop: '#E4C0D8',
      bgMid: '#FBF4F9',
      bgBottom: '#DCC0D0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#220A1C',
      textMid: '#5E1A48',
      textDim: '#A06888',
    },
    dark: {
      scheme: 'dark',
      accent: '#D05898',
      accentLight: 'rgba(208,88,152,0.18)',
      bgTop: '#160818',
      bgMid: '#220E26',
      bgBottom: '#0E0410',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F0E0EC',
      textMid: '#C088A8',
      textDim: '#705878',
    },
  },
  {
    id: 'bronze-gate',
    name: 'Bronze Gate',
    light: {
      scheme: 'light',
      accent: '#8A5E18',
      accentLight: '#FAF0D0',
      bgTop: '#F0E0A8',
      bgMid: '#FDF9F0',
      bgBottom: '#EAD8B0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#221400',
      textMid: '#634800',
      textDim: '#AA8840',
    },
    dark: {
      scheme: 'dark',
      accent: '#E0AA48',
      accentLight: 'rgba(224,170,72,0.18)',
      bgTop: '#181200',
      bgMid: '#241A02',
      bgBottom: '#100C00',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FAF0D0',
      textMid: '#C8A858',
      textDim: '#786838',
    },
  },
  {
    id: 'bukhara-silk',
    name: 'Bukhara Silk',
    light: {
      scheme: 'light',
      accent: '#A82850',
      accentLight: '#FAE0E8',
      bgTop: '#F4C8D4',
      bgMid: '#FEF4F7',
      bgBottom: '#ECBCCC',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2A0818',
      textMid: '#701838',
      textDim: '#B07088',
    },
    dark: {
      scheme: 'dark',
      accent: '#E06088',
      accentLight: 'rgba(224,96,136,0.18)',
      bgTop: '#1E0810',
      bgMid: '#2C0E18',
      bgBottom: '#14040A',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FAE0E8',
      textMid: '#C880A0',
      textDim: '#784858',
    },
  },
  {
    id: 'calligraphy-ink',
    name: 'Calligraphy Ink',
    light: {
      scheme: 'light',
      accent: '#1A2A4A',
      accentLight: '#E0E4ED',
      bgTop: '#C8D0DC',
      bgMid: '#F2F4F8',
      bgBottom: '#D4DCE6',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#050810',
      textMid: '#1A2438',
      textDim: '#707888',
    },
    dark: {
      scheme: 'dark',
      accent: '#6080B8',
      accentLight: 'rgba(96,128,184,0.18)',
      bgTop: '#050810',
      bgMid: '#0A0E1A',
      bgBottom: '#02040A',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#E0E4ED',
      textMid: '#98A0B8',
      textDim: '#506078',
    },
  },
  {
    id: 'cardamom-mist',
    name: 'Cardamom Mist',
    light: {
      scheme: 'light',
      accent: '#5A8070',
      accentLight: '#E8F0EC',
      bgTop: '#D4E4DC',
      bgMid: '#F4F8F6',
      bgBottom: '#DCE8E0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#0A1A14',
      textMid: '#2E4A40',
      textDim: '#80A498',
    },
    dark: {
      scheme: 'dark',
      accent: '#98C8B0',
      accentLight: 'rgba(152,200,176,0.18)',
      bgTop: '#0A1410',
      bgMid: '#121C18',
      bgBottom: '#06100C',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#E8F0EC',
      textMid: '#A0B8AC',
      textDim: '#607870',
    },
  },
  {
    id: 'cedar-path',
    name: 'Cedar Path',
    light: {
      scheme: 'light',
      accent: '#7A4520',
      accentLight: '#F5E8DC',
      bgTop: '#EDCFB8',
      bgMid: '#FBF5F0',
      bgBottom: '#F0D8C4',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2A1508',
      textMid: '#5C3A20',
      textDim: '#A88060',
    },
    dark: {
      scheme: 'dark',
      accent: '#D4956A',
      accentLight: 'rgba(212,149,106,0.18)',
      bgTop: '#1C1008',
      bgMid: '#281608',
      bgBottom: '#120A04',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F5E8DC',
      textMid: '#C8A880',
      textDim: '#786050',
    },
  },
  {
    id: 'cinnamon-spice',
    name: 'Cinnamon Spice',
    light: {
      scheme: 'light',
      accent: '#B04828',
      accentLight: '#FAEBE0',
      bgTop: '#F2CEBC',
      bgMid: '#FEF5EF',
      bgBottom: '#EAC8B4',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2A1008',
      textMid: '#6A3A20',
      textDim: '#AA8060',
    },
    dark: {
      scheme: 'dark',
      accent: '#E87A50',
      accentLight: 'rgba(232,122,80,0.18)',
      bgTop: '#1E0A04',
      bgMid: '#2C1408',
      bgBottom: '#140804',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FAEBE0',
      textMid: '#C09070',
      textDim: '#745A48',
    },
  },
  {
    id: 'clay-dusk',
    name: 'Clay Dusk',
    light: {
      scheme: 'light',
      accent: '#9E5830',
      accentLight: '#FAE8DC',
      bgTop: '#F0D0BA',
      bgMid: '#FCF5F0',
      bgBottom: '#E8C8B0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#271208',
      textMid: '#663C20',
      textDim: '#AA8060',
    },
    dark: {
      scheme: 'dark',
      accent: '#E0905A',
      accentLight: 'rgba(224,144,90,0.18)',
      bgTop: '#1C0E06',
      bgMid: '#281408',
      bgBottom: '#120804',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FAE8DC',
      textMid: '#C09870',
      textDim: '#74584A',
    },
  },
  {
    id: 'copper-arch',
    name: 'Copper Arch',
    light: {
      scheme: 'light',
      accent: '#9E4A28',
      accentLight: '#FBEADE',
      bgTop: '#F5D4C0',
      bgMid: '#FEF5F0',
      bgBottom: '#EDCAB8',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2A1008',
      textMid: '#6A3818',
      textDim: '#B08060',
    },
    dark: {
      scheme: 'dark',
      accent: '#E8885A',
      accentLight: 'rgba(232,136,90,0.18)',
      bgTop: '#1E0E06',
      bgMid: '#2C1508',
      bgBottom: '#140804',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FBEADE',
      textMid: '#C89870',
      textDim: '#786048',
    },
  },
  {
    id: 'coral-bloom',
    name: 'Coral Bloom',
    light: {
      scheme: 'light',
      accent: '#C05040',
      accentLight: '#FAECE8',
      bgTop: '#F5D0C8',
      bgMid: '#FEF7F5',
      bgBottom: '#EEC8C0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2C100C',
      textMid: '#7A3028',
      textDim: '#B88078',
    },
    dark: {
      scheme: 'dark',
      accent: '#F08870',
      accentLight: 'rgba(240,136,112,0.18)',
      bgTop: '#1E0C08',
      bgMid: '#2C1410',
      bgBottom: '#140804',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FAECE8',
      textMid: '#C8988A',
      textDim: '#7A5850',
    },
  },
  {
    id: 'crescent-glow',
    name: 'Crescent Glow',
    light: {
      scheme: 'light',
      accent: '#788090',
      accentLight: '#ECEEF2',
      bgTop: '#D8DDE5',
      bgMid: '#F6F7F9',
      bgBottom: '#DEE3E9',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#181A22',
      textMid: '#404550',
      textDim: '#888E9A',
    },
    dark: {
      scheme: 'dark',
      accent: '#B8C0CC',
      accentLight: 'rgba(184,192,204,0.18)',
      bgTop: '#0C0E12',
      bgMid: '#16191E',
      bgBottom: '#060708',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#ECEEF2',
      textMid: '#A0A8B4',
      textDim: '#606878',
    },
  },
  {
    id: 'crimson-dusk',
    name: 'Rikhil Radiance',
    light: {
      scheme: 'light',
      accent: '#9B1C2E',
      accentLight: '#FAEAEC',
      bgTop: '#F2D0D4',
      bgMid: '#FDF5F6',
      bgBottom: '#EDD5D8',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#280810',
      textMid: '#6A2C36',
      textDim: '#B48088',
    },
    dark: {
      scheme: 'dark',
      accent: '#F07080',
      accentLight: 'rgba(240,112,128,0.18)',
      bgTop: '#1A0408',
      bgMid: '#280A10',
      bgBottom: '#110204',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FAEAEC',
      textMid: '#C8969E',
      textDim: '#7A5058',
    },
  },
  {
    id: 'damascus-steel',
    name: 'Damascus Steel',
    light: {
      scheme: 'light',
      accent: '#4E6A78',
      accentLight: '#E4EBEE',
      bgTop: '#CCD8DD',
      bgMid: '#F4F6F8',
      bgBottom: '#D8E0E4',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#0E181E',
      textMid: '#324048',
      textDim: '#80909A',
    },
    dark: {
      scheme: 'dark',
      accent: '#98B8C8',
      accentLight: 'rgba(152,184,200,0.18)',
      bgTop: '#080C10',
      bgMid: '#121820',
      bgBottom: '#04060A',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#E4EBEE',
      textMid: '#A0B0BC',
      textDim: '#586878',
    },
  },
  {
    id: 'date-palm',
    name: 'Date Palm',
    light: {
      scheme: 'light',
      accent: '#3A2818',
      accentLight: '#ECE4DC',
      bgTop: '#DCCCB8',
      bgMid: '#F8F2EC',
      bgBottom: '#D4C4B0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#100804',
      textMid: '#2E1F10',
      textDim: '#806858',
    },
    dark: {
      scheme: 'dark',
      accent: '#A88068',
      accentLight: 'rgba(168,128,104,0.18)',
      bgTop: '#100804',
      bgMid: '#1A1208',
      bgBottom: '#080404',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#ECE4DC',
      textMid: '#B89880',
      textDim: '#6A5040',
    },
  },
  {
    id: 'dome-gold',
    name: 'Dome Gold',
    light: {
      scheme: 'light',
      accent: '#A07820',
      accentLight: '#FAF0D0',
      bgTop: '#F4E4A8',
      bgMid: '#FDF9F0',
      bgBottom: '#ECDCA0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#221800',
      textMid: '#6A5418',
      textDim: '#B09848',
    },
    dark: {
      scheme: 'dark',
      accent: '#E8C060',
      accentLight: 'rgba(232,192,96,0.18)',
      bgTop: '#181200',
      bgMid: '#241A00',
      bgBottom: '#100C00',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FAF0D0',
      textMid: '#C8A858',
      textDim: '#786838',
    },
  },
  {
    id: 'dusty-rose',
    name: 'Dusty Rose',
    light: {
      scheme: 'light',
      accent: '#9A5A6A',
      accentLight: '#F8ECF0',
      bgTop: '#F0D8DE',
      bgMid: '#FDF8F9',
      bgBottom: '#EAD4D8',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2A1018',
      textMid: '#6A3A45',
      textDim: '#B09098',
    },
    dark: {
      scheme: 'dark',
      accent: '#D89098',
      accentLight: 'rgba(216,144,152,0.18)',
      bgTop: '#1A080E',
      bgMid: '#260D14',
      bgBottom: '#120408',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F8ECF0',
      textMid: '#C8A0A8',
      textDim: '#7A5860',
    },
  },
  {
    id: 'eid-bloom',
    name: 'Eid Bloom',
    light: {
      scheme: 'light',
      accent: '#C04088',
      accentLight: '#FAE0EE',
      bgTop: '#F4C0DC',
      bgMid: '#FEF4F8',
      bgBottom: '#EAB8D0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2A0820',
      textMid: '#702048',
      textDim: '#B070A0',
    },
    dark: {
      scheme: 'dark',
      accent: '#F088C0',
      accentLight: 'rgba(240,136,192,0.18)',
      bgTop: '#1E0816',
      bgMid: '#2C0E22',
      bgBottom: '#14040E',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FAE0EE',
      textMid: '#C880B0',
      textDim: '#785080',
    },
  },
  {
    id: 'emerald-gate',
    name: 'Emerald Gate',
    light: {
      scheme: 'light',
      accent: '#0A7A50',
      accentLight: '#D8F5EA',
      bgTop: '#ACEEDD',
      bgMid: '#EDFFFB',
      bgBottom: '#C0F0E4',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#041E18',
      textMid: '#1A6050',
      textDim: '#68AE98',
    },
    dark: {
      scheme: 'dark',
      accent: '#40D890',
      accentLight: 'rgba(64,216,144,0.18)',
      bgTop: '#041410',
      bgMid: '#082018',
      bgBottom: '#020C08',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#D8F5EA',
      textMid: '#88C8A8',
      textDim: '#488068',
    },
  },
  {
    id: 'fajr-mist',
    name: 'Fajr Mist',
    light: {
      scheme: 'light',
      accent: '#B86A48',
      accentLight: '#FBEAE0',
      bgTop: '#F5D4C0',
      bgMid: '#FFF5F0',
      bgBottom: '#EDC8B0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2A1408',
      textMid: '#703820',
      textDim: '#B08060',
    },
    dark: {
      scheme: 'dark',
      accent: '#F0B080',
      accentLight: 'rgba(240,176,128,0.18)',
      bgTop: '#1E0E06',
      bgMid: '#2A1408',
      bgBottom: '#140804',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FBEAE0',
      textMid: '#C89880',
      textDim: '#785A40',
    },
  },
  {
    id: 'fez-tile',
    name: 'Fez Tile',
    light: {
      scheme: 'light',
      accent: '#1A4880',
      accentLight: '#DCE6F4',
      bgTop: '#BCD0EE',
      bgMid: '#EEF4FC',
      bgBottom: '#C8DCF0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#050C20',
      textMid: '#1E3460',
      textDim: '#708CB0',
    },
    dark: {
      scheme: 'dark',
      accent: '#5090D0',
      accentLight: 'rgba(80,144,208,0.18)',
      bgTop: '#050C18',
      bgMid: '#0C1424',
      bgBottom: '#04080F',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#DCE6F4',
      textMid: '#88A8C8',
      textDim: '#506880',
    },
  },
  {
    id: 'fig-garden',
    name: 'Fig Garden',
    light: {
      scheme: 'light',
      accent: '#5E2A58',
      accentLight: '#EEE0F0',
      bgTop: '#DEC8E0',
      bgMid: '#F8F2F9',
      bgBottom: '#DAC8DC',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1C0C1E',
      textMid: '#4E2050',
      textDim: '#9870A0',
    },
    dark: {
      scheme: 'dark',
      accent: '#C868C0',
      accentLight: 'rgba(200,104,192,0.18)',
      bgTop: '#120818',
      bgMid: '#1C0C24',
      bgBottom: '#0A0410',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#EEE0F0',
      textMid: '#B888B8',
      textDim: '#6A5070',
    },
  },
  {
    id: 'forest-sahn',
    name: 'Forest Sahn',
    light: {
      scheme: 'light',
      accent: '#205030',
      accentLight: '#DFF0E4',
      bgTop: '#C0E4CA',
      bgMid: '#EFF8F2',
      bgBottom: '#CDE8D4',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#081A10',
      textMid: '#1E4028',
      textDim: '#70A080',
    },
    dark: {
      scheme: 'dark',
      accent: '#58C870',
      accentLight: 'rgba(88,200,112,0.18)',
      bgTop: '#061210',
      bgMid: '#0A1C12',
      bgBottom: '#040C08',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#DFF0E4',
      textMid: '#90C8A0',
      textDim: '#508060',
    },
  },
  {
    id: 'frankincense-glow',
    name: 'Frankincense Glow',
    light: {
      scheme: 'light',
      accent: '#7A5A28',
      accentLight: '#F8EFD8',
      bgTop: '#EEDDB0',
      bgMid: '#FDFAF0',
      bgBottom: '#E4D098',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1E1400',
      textMid: '#5A4818',
      textDim: '#A89460',
    },
    dark: {
      scheme: 'dark',
      accent: '#C8A058',
      accentLight: 'rgba(200,160,88,0.18)',
      bgTop: '#161000',
      bgMid: '#221800',
      bgBottom: '#0E0A00',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F8EFD8',
      textMid: '#C09870',
      textDim: '#786040',
    },
  },
  {
    id: 'golden-sands',
    name: 'Golden Sands',
    light: {
      scheme: 'light',
      accent: '#A67C00',
      accentLight: '#FBF3DC',
      bgTop: '#F5E8B0',
      bgMid: '#FDFAF0',
      bgBottom: '#F0E5C0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#241A00',
      textMid: '#6B5500',
      textDim: '#B8A060',
    },
    dark: {
      scheme: 'dark',
      accent: '#F0C84A',
      accentLight: 'rgba(240,200,74,0.18)',
      bgTop: '#1A1400',
      bgMid: '#261E05',
      bgBottom: '#120E00',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FBF3DC',
      textMid: '#C8B87A',
      textDim: '#7A6E40',
    },
  },
  {
    id: 'granada-bloom',
    name: 'Granada Bloom',
    light: {
      scheme: 'light',
      accent: '#A82820',
      accentLight: '#FADCD8',
      bgTop: '#F4BCB4',
      bgMid: '#FEF3F0',
      bgBottom: '#EBB0A8',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2A0804',
      textMid: '#701810',
      textDim: '#B07060',
    },
    dark: {
      scheme: 'dark',
      accent: '#E86850',
      accentLight: 'rgba(232,104,80,0.18)',
      bgTop: '#1E0804',
      bgMid: '#2C0E06',
      bgBottom: '#14040A',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FADCD8',
      textMid: '#C88878',
      textDim: '#785848',
    },
  },
  {
    id: 'hajj-sand',
    name: 'Hajj Sand',
    light: {
      scheme: 'light',
      accent: '#8A7050',
      accentLight: '#F5EBDC',
      bgTop: '#ECDCC0',
      bgMid: '#FBF6EE',
      bgBottom: '#E4D0B0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#20180A',
      textMid: '#584830',
      textDim: '#A89070',
    },
    dark: {
      scheme: 'dark',
      accent: '#D4B888',
      accentLight: 'rgba(212,184,136,0.18)',
      bgTop: '#181208',
      bgMid: '#221A0C',
      bgBottom: '#100C04',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F5EBDC',
      textMid: '#C8A888',
      textDim: '#786A50',
    },
  },
  {
    id: 'hazel-dusk',
    name: 'Hazel Dusk',
    light: {
      scheme: 'light',
      accent: '#7A5E30',
      accentLight: '#F5EDDC',
      bgTop: '#EAD8B8',
      bgMid: '#FBF7F0',
      bgBottom: '#E6D4B4',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#241808',
      textMid: '#5A4020',
      textDim: '#A88C60',
    },
    dark: {
      scheme: 'dark',
      accent: '#C8A060',
      accentLight: 'rgba(200,160,96,0.18)',
      bgTop: '#1A1408',
      bgMid: '#241C0A',
      bgBottom: '#100C04',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F5EDDC',
      textMid: '#C0A870',
      textDim: '#74604A',
    },
  },
  {
    id: 'henna-hue',
    name: 'Henna Hue',
    light: {
      scheme: 'light',
      accent: '#7A2818',
      accentLight: '#F4DDD8',
      bgTop: '#ECBCB0',
      bgMid: '#FCF1ED',
      bgBottom: '#E0AA9C',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#200804',
      textMid: '#5A1C10',
      textDim: '#A87060',
    },
    dark: {
      scheme: 'dark',
      accent: '#C86040',
      accentLight: 'rgba(200,96,64,0.18)',
      bgTop: '#1A0804',
      bgMid: '#261004',
      bgBottom: '#100604',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F4DDD8',
      textMid: '#C08070',
      textDim: '#785848',
    },
  },
  {
    id: 'honey-comb',
    name: 'Honey Comb',
    light: {
      scheme: 'light',
      accent: '#B08010',
      accentLight: '#FBF0CC',
      bgTop: '#F5E098',
      bgMid: '#FEFAEC',
      bgBottom: '#EBCE80',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#221800',
      textMid: '#6A5008',
      textDim: '#B09838',
    },
    dark: {
      scheme: 'dark',
      accent: '#F0C038',
      accentLight: 'rgba(240,192,56,0.18)',
      bgTop: '#1A1400',
      bgMid: '#281E00',
      bgBottom: '#120E00',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FBF0CC',
      textMid: '#C8AC58',
      textDim: '#786838',
    },
  },
  {
    id: 'iftar-glow',
    name: 'Iftar Glow',
    light: {
      scheme: 'light',
      accent: '#B05020',
      accentLight: '#FAE2D2',
      bgTop: '#F4C8AC',
      bgMid: '#FEF3EC',
      bgBottom: '#EAB48E',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#28100A',
      textMid: '#6A3010',
      textDim: '#B07A50',
    },
    dark: {
      scheme: 'dark',
      accent: '#E88848',
      accentLight: 'rgba(232,136,72,0.18)',
      bgTop: '#1E0C04',
      bgMid: '#2C1408',
      bgBottom: '#140804',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FAE2D2',
      textMid: '#C89070',
      textDim: '#786040',
    },
  },
  {
    id: 'indigo-night',
    name: 'Indigo Night',
    light: {
      scheme: 'light',
      accent: '#5B3FAA',
      accentLight: '#ECE6F7',
      bgTop: '#DCD3F0',
      bgMid: '#F5F1FB',
      bgBottom: '#E5DCF1',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1A102E',
      textMid: '#4F3F70',
      textDim: '#9489B0',
    },
    dark: {
      scheme: 'dark',
      accent: '#B49EFF',
      accentLight: 'rgba(180,158,255,0.18)',
      bgTop: '#110A1F',
      bgMid: '#1B102E',
      bgBottom: '#0B0617',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#ECE6F7',
      textMid: '#B5A8D1',
      textDim: '#6E658C',
    },
  },
  {
    id: 'isfahan-tile',
    name: 'Isfahan Tile',
    light: {
      scheme: 'light',
      accent: '#1830A0',
      accentLight: '#DCDFF8',
      bgTop: '#BCC4EE',
      bgMid: '#EFF0FB',
      bgBottom: '#C8D0F0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#04081E',
      textMid: '#1A2868',
      textDim: '#6878B0',
    },
    dark: {
      scheme: 'dark',
      accent: '#5070E0',
      accentLight: 'rgba(80,112,224,0.18)',
      bgTop: '#04081E',
      bgMid: '#0A1028',
      bgBottom: '#02050E',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#DCDFF8',
      textMid: '#88A0D8',
      textDim: '#506888',
    },
  },
  {
    id: 'isha-dusk',
    name: 'Isha Dusk',
    light: {
      scheme: 'light',
      accent: '#2A1850',
      accentLight: '#E0DAF0',
      bgTop: '#C8BEE4',
      bgMid: '#F2F0FA',
      bgBottom: '#D0C8E8',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#080418',
      textMid: '#1E1440',
      textDim: '#806EAC',
    },
    dark: {
      scheme: 'dark',
      accent: '#6048A8',
      accentLight: 'rgba(96,72,168,0.18)',
      bgTop: '#0A0418',
      bgMid: '#110828',
      bgBottom: '#050410',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#E0DAF0',
      textMid: '#A090C8',
      textDim: '#585070',
    },
  },
  {
    id: 'ivory-gate',
    name: 'Ivory Gate',
    light: {
      scheme: 'light',
      accent: '#9A8060',
      accentLight: '#F8F3EA',
      bgTop: '#F0E8D4',
      bgMid: '#FDFBF7',
      bgBottom: '#ECE4D4',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#24200C',
      textMid: '#6A5840',
      textDim: '#B0A080',
    },
    dark: {
      scheme: 'dark',
      accent: '#D4C090',
      accentLight: 'rgba(212,192,144,0.18)',
      bgTop: '#181408',
      bgMid: '#241E10',
      bgBottom: '#100C04',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F8F3EA',
      textMid: '#C4B080',
      textDim: '#747050',
    },
  },
  {
    id: 'iznik-bloom',
    name: 'Iznik Bloom',
    light: {
      scheme: 'light',
      accent: '#208090',
      accentLight: '#DCEDF0',
      bgTop: '#B4E0E8',
      bgMid: '#EFF8FA',
      bgBottom: '#C0E4EA',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#08242A',
      textMid: '#1A6068',
      textDim: '#66ACB0',
    },
    dark: {
      scheme: 'dark',
      accent: '#60C0D0',
      accentLight: 'rgba(96,192,208,0.18)',
      bgTop: '#04141A',
      bgMid: '#0A2028',
      bgBottom: '#030C10',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#DCEDF0',
      textMid: '#88BAC8',
      textDim: '#487888',
    },
  },
  {
    id: 'kaaba-veil',
    name: 'Kaaba Veil',
    light: {
      scheme: 'light',
      accent: '#1A1410',
      accentLight: '#E8E4E0',
      bgTop: '#D4CDC4',
      bgMid: '#F4F2F0',
      bgBottom: '#DCD4CC',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#050404',
      textMid: '#1E1A14',
      textDim: '#807868',
    },
    dark: {
      scheme: 'dark',
      accent: '#A89880',
      accentLight: 'rgba(168,152,128,0.18)',
      bgTop: '#0A0806',
      bgMid: '#14100C',
      bgBottom: '#060404',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#E8E4E0',
      textMid: '#A09888',
      textDim: '#605848',
    },
  },
  {
    id: 'kiswa-gold',
    name: 'Kiswa Gold',
    light: {
      scheme: 'light',
      accent: '#5A4818',
      accentLight: '#F0E4C0',
      bgTop: '#E0CC88',
      bgMid: '#FAF4E0',
      bgBottom: '#D8C078',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1A1400',
      textMid: '#443808',
      textDim: '#A08C40',
    },
    dark: {
      scheme: 'dark',
      accent: '#B89848',
      accentLight: 'rgba(184,152,72,0.18)',
      bgTop: '#100C00',
      bgMid: '#1A1400',
      bgBottom: '#080604',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F0E4C0',
      textMid: '#B89C58',
      textDim: '#685838',
    },
  },
  {
    id: 'lapis-luqman',
    name: 'Lapis Luqman',
    light: {
      scheme: 'light',
      accent: '#0057B8',
      accentLight: '#E0EDFF',
      bgTop: '#C8DEFF',
      bgMid: '#F0F6FF',
      bgBottom: '#D4E6FF',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#001830',
      textMid: '#2A4E7A',
      textDim: '#7A9BBF',
    },
    dark: {
      scheme: 'dark',
      accent: '#5EA4FF',
      accentLight: 'rgba(94,164,255,0.18)',
      bgTop: '#00101F',
      bgMid: '#071A2E',
      bgBottom: '#000A16',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#E0EDFF',
      textMid: '#90B8E0',
      textDim: '#506A88',
    },
  },
  {
    id: 'lavender-mist',
    name: 'Lavender Mist',
    light: {
      scheme: 'light',
      accent: '#7A5AB0',
      accentLight: '#EDE8F8',
      bgTop: '#DDD4F4',
      bgMid: '#F6F3FB',
      bgBottom: '#E4DEF2',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1E1030',
      textMid: '#5A4080',
      textDim: '#9A88BC',
    },
    dark: {
      scheme: 'dark',
      accent: '#B898F0',
      accentLight: 'rgba(184,152,240,0.18)',
      bgTop: '#100C22',
      bgMid: '#1A1432',
      bgBottom: '#0A0818',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#EDE8F8',
      textMid: '#B5A0D8',
      textDim: '#6C5888',
    },
  },
  {
    id: 'madinah-green',
    name: 'Madinah Green',
    light: {
      scheme: 'light',
      accent: '#1A6840',
      accentLight: '#DCF0E4',
      bgTop: '#B4E4C8',
      bgMid: '#EFF8F2',
      bgBottom: '#C4E8D0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#04180E',
      textMid: '#1A4830',
      textDim: '#68A088',
    },
    dark: {
      scheme: 'dark',
      accent: '#58C088',
      accentLight: 'rgba(88,192,136,0.18)',
      bgTop: '#04140A',
      bgMid: '#0A1E14',
      bgBottom: '#020C08',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#DCF0E4',
      textMid: '#88C0A0',
      textDim: '#487058',
    },
  },
  {
    id: 'maghrib-sky',
    name: 'Maghrib Sky',
    light: {
      scheme: 'light',
      accent: '#A8385C',
      accentLight: '#FAE0E8',
      bgTop: '#F4C0CC',
      bgMid: '#FEF4F6',
      bgBottom: '#ECB4C0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#28080E',
      textMid: '#701830',
      textDim: '#B07088',
    },
    dark: {
      scheme: 'dark',
      accent: '#E07088',
      accentLight: 'rgba(224,112,136,0.18)',
      bgTop: '#1C0810',
      bgMid: '#281018',
      bgBottom: '#14040A',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FAE0E8',
      textMid: '#C880A0',
      textDim: '#785868',
    },
  },
  {
    id: 'marble-sahn',
    name: 'Marble Sahn',
    light: {
      scheme: 'light',
      accent: '#5A6066',
      accentLight: '#ECF0F2',
      bgTop: '#D8E0E4',
      bgMid: '#F6F8F9',
      bgBottom: '#E0E6E8',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#141820',
      textMid: '#3E484E',
      textDim: '#869298',
    },
    dark: {
      scheme: 'dark',
      accent: '#98A8B0',
      accentLight: 'rgba(152,168,176,0.18)',
      bgTop: '#0C1016',
      bgMid: '#141A20',
      bgBottom: '#080C10',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#ECF0F2',
      textMid: '#A0B0B8',
      textDim: '#607078',
    },
  },
  {
    id: 'marrakech-sun',
    name: 'Marrakech Sun',
    light: {
      scheme: 'light',
      accent: '#B85820',
      accentLight: '#FAE4D0',
      bgTop: '#F4CCA8',
      bgMid: '#FEF5EC',
      bgBottom: '#ECB888',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#281008',
      textMid: '#6A3818',
      textDim: '#B07840',
    },
    dark: {
      scheme: 'dark',
      accent: '#F08838',
      accentLight: 'rgba(240,136,56,0.18)',
      bgTop: '#1E0E04',
      bgMid: '#2A1408',
      bgBottom: '#14080C',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FAE4D0',
      textMid: '#C89060',
      textDim: '#785838',
    },
  },
  {
    id: 'mauve-arch',
    name: 'Mauve Arch',
    light: {
      scheme: 'light',
      accent: '#8A5070',
      accentLight: '#F4ECF2',
      bgTop: '#E8D4E0',
      bgMid: '#FBF6F9',
      bgBottom: '#E0CCD8',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#24101E',
      textMid: '#5E3050',
      textDim: '#A880A0',
    },
    dark: {
      scheme: 'dark',
      accent: '#C890B0',
      accentLight: 'rgba(200,144,176,0.18)',
      bgTop: '#160C12',
      bgMid: '#20101C',
      bgBottom: '#0C0808',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F4ECF2',
      textMid: '#C090A8',
      textDim: '#706070',
    },
  },
  {
    id: 'minaret-sky',
    name: 'Minaret Sky',
    light: {
      scheme: 'light',
      accent: '#3080B0',
      accentLight: '#DCEAF4',
      bgTop: '#B4D8EE',
      bgMid: '#EFF7FC',
      bgBottom: '#C4E0EE',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#04141E',
      textMid: '#1A5070',
      textDim: '#6090B0',
    },
    dark: {
      scheme: 'dark',
      accent: '#80C0E0',
      accentLight: 'rgba(128,192,224,0.18)',
      bgTop: '#04101C',
      bgMid: '#0A1A28',
      bgBottom: '#03080E',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#DCEAF4',
      textMid: '#88B0CC',
      textDim: '#506888',
    },
  },
  {
    id: 'mint-breeze',
    name: 'Mint Breeze',
    light: {
      scheme: 'light',
      accent: '#1A8A6E',
      accentLight: '#DFF5EF',
      bgTop: '#BEEEE2',
      bgMid: '#F0FAF7',
      bgBottom: '#CEEEE6',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#082820',
      textMid: '#2E6A58',
      textDim: '#7AB0A0',
    },
    dark: {
      scheme: 'dark',
      accent: '#50D4B0',
      accentLight: 'rgba(80,212,176,0.18)',
      bgTop: '#041410',
      bgMid: '#0A201A',
      bgBottom: '#020C08',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#DFF5EF',
      textMid: '#90C8B8',
      textDim: '#507868',
    },
  },
  {
    id: 'mulberry-glow',
    name: 'Mulberry Glow',
    light: {
      scheme: 'light',
      accent: '#5A1838',
      accentLight: '#F0DCE6',
      bgTop: '#E0B8CC',
      bgMid: '#FBF0F4',
      bgBottom: '#D8A8C0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1A0410',
      textMid: '#3E0824',
      textDim: '#885070',
    },
    dark: {
      scheme: 'dark',
      accent: '#B05078',
      accentLight: 'rgba(176,80,120,0.18)',
      bgTop: '#160410',
      bgMid: '#200818',
      bgBottom: '#0C040C',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F0DCE6',
      textMid: '#B8809A',
      textDim: '#685058',
    },
  },
  {
    id: 'myrrh-smoke',
    name: 'Myrrh Smoke',
    light: {
      scheme: 'light',
      accent: '#4A3828',
      accentLight: '#ECE4DC',
      bgTop: '#DCCFC0',
      bgMid: '#F8F2EC',
      bgBottom: '#D4C2B0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#100804',
      textMid: '#2A1F14',
      textDim: '#806A58',
    },
    dark: {
      scheme: 'dark',
      accent: '#98806C',
      accentLight: 'rgba(152,128,108,0.18)',
      bgTop: '#100C08',
      bgMid: '#1A1410',
      bgBottom: '#080604',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#ECE4DC',
      textMid: '#B89888',
      textDim: '#6A5848',
    },
  },
  {
    id: 'nile-silt',
    name: 'Nile Silt',
    light: {
      scheme: 'light',
      accent: '#6A6A28',
      accentLight: '#F4F0D4',
      bgTop: '#E8E0A8',
      bgMid: '#FAF8E8',
      bgBottom: '#DCD498',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1E1E08',
      textMid: '#4E4E18',
      textDim: '#989858',
    },
    dark: {
      scheme: 'dark',
      accent: '#C0B868',
      accentLight: 'rgba(192,184,104,0.18)',
      bgTop: '#14140A',
      bgMid: '#20200E',
      bgBottom: '#0C0C04',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F4F0D4',
      textMid: '#B8B070',
      textDim: '#686848',
    },
  },
  {
    id: 'ochre-trail',
    name: 'Ochre Trail',
    light: {
      scheme: 'light',
      accent: '#9A7020',
      accentLight: '#FAF0D0',
      bgTop: '#F0E0A0',
      bgMid: '#FDFAF0',
      bgBottom: '#EAD898',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#221800',
      textMid: '#6A5010',
      textDim: '#B09840',
    },
    dark: {
      scheme: 'dark',
      accent: '#E0B848',
      accentLight: 'rgba(224,184,72,0.18)',
      bgTop: '#181200',
      bgMid: '#241A00',
      bgBottom: '#100C00',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FAF0D0',
      textMid: '#C8A858',
      textDim: '#786838',
    },
  },
  {
    id: 'olive-grove',
    name: 'Olive Grove',
    light: {
      scheme: 'light',
      accent: '#6B7A2A',
      accentLight: '#F1F4DC',
      bgTop: '#E0E5C5',
      bgMid: '#F8F8EC',
      bgBottom: '#E5E8D2',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1F230D',
      textMid: '#4F5530',
      textDim: '#9BA170',
    },
    dark: {
      scheme: 'dark',
      accent: '#C4D26E',
      accentLight: 'rgba(196,210,110,0.18)',
      bgTop: '#11140A',
      bgMid: '#1B1F11',
      bgBottom: '#090C05',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F1F4DC',
      textMid: '#B7BC95',
      textDim: '#6F7459',
    },
  },
  {
    id: 'oud-wood',
    name: 'Oud Wood',
    light: {
      scheme: 'light',
      accent: '#2A1808',
      accentLight: '#ECDCD0',
      bgTop: '#D4BCA8',
      bgMid: '#F4ECE4',
      bgBottom: '#C8B098',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#0A0404',
      textMid: '#1E1408',
      textDim: '#6A5848',
    },
    dark: {
      scheme: 'dark',
      accent: '#885838',
      accentLight: 'rgba(136,88,56,0.18)',
      bgTop: '#100804',
      bgMid: '#1A1004',
      bgBottom: '#080404',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#ECDCD0',
      textMid: '#B89878',
      textDim: '#6A5040',
    },
  },
  {
    id: 'pearl-dust',
    name: 'Pearl Dust',
    light: {
      scheme: 'light',
      accent: '#5A6577',
      accentLight: '#ECEEF2',
      bgTop: '#DDE2EA',
      bgMid: '#F6F7F9',
      bgBottom: '#E4E7ED',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1A1F2A',
      textMid: '#4A5260',
      textDim: '#99A2B0',
    },
    dark: {
      scheme: 'dark',
      accent: '#A8B5CC',
      accentLight: 'rgba(168,181,204,0.18)',
      bgTop: '#0E1116',
      bgMid: '#181C24',
      bgBottom: '#07090C',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#ECEEF2',
      textMid: '#ABB2BF',
      textDim: '#6A7280',
    },
  },
  {
    id: 'pearl-hijaz',
    name: 'Shahir Silk',
    light: {
      scheme: 'light',
      accent: '#807870',
      accentLight: '#F4F0EC',
      bgTop: '#E0DCD4',
      bgMid: '#FAF8F5',
      bgBottom: '#ECE4DC',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1A1814',
      textMid: '#44403A',
      textDim: '#8A847A',
    },
    dark: {
      scheme: 'dark',
      accent: '#C8C0B8',
      accentLight: 'rgba(200,192,184,0.18)',
      bgTop: '#100E0C',
      bgMid: '#1A1814',
      bgBottom: '#080604',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F4F0EC',
      textMid: '#B0A89E',
      textDim: '#686058',
    },
  },
  {
    id: 'persian-gulf',
    name: 'Persian Gulf',
    light: {
      scheme: 'light',
      accent: '#1860A0',
      accentLight: '#DCE8F4',
      bgTop: '#BCD4EE',
      bgMid: '#EFF4FC',
      bgBottom: '#C8DEEE',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#04101E',
      textMid: '#1A4068',
      textDim: '#708CB0',
    },
    dark: {
      scheme: 'dark',
      accent: '#6098D0',
      accentLight: 'rgba(96,152,208,0.18)',
      bgTop: '#040C1A',
      bgMid: '#0A1424',
      bgBottom: '#03060E',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#DCE8F4',
      textMid: '#88B0CC',
      textDim: '#50688A',
    },
  },
  {
    id: 'pistachio-court',
    name: 'Pistachio Court',
    light: {
      scheme: 'light',
      accent: '#5A7028',
      accentLight: '#F0F4D8',
      bgTop: '#DCE8A0',
      bgMid: '#FAFCEC',
      bgBottom: '#C8D898',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#181F08',
      textMid: '#3E4E18',
      textDim: '#989838',
    },
    dark: {
      scheme: 'dark',
      accent: '#B0C868',
      accentLight: 'rgba(176,200,104,0.18)',
      bgTop: '#10140A',
      bgMid: '#1C220E',
      bgBottom: '#080C04',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F0F4D8',
      textMid: '#B0B870',
      textDim: '#687048',
    },
  },
  {
    id: 'plum-night',
    name: 'Plum Night',
    light: {
      scheme: 'light',
      accent: '#6A2A5E',
      accentLight: '#EFE0EC',
      bgTop: '#E0C4DC',
      bgMid: '#F8F0F7',
      bgBottom: '#DCC8D8',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1E0A1A',
      textMid: '#502044',
      textDim: '#9870A0',
    },
    dark: {
      scheme: 'dark',
      accent: '#D070C0',
      accentLight: 'rgba(208,112,192,0.18)',
      bgTop: '#140820',
      bgMid: '#1E0C2E',
      bgBottom: '#0C0412',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#EFE0EC',
      textMid: '#C090B8',
      textDim: '#705888',
    },
  },
  {
    id: 'pomegranate-court',
    name: 'Garnet Court',
    light: {
      scheme: 'light',
      accent: '#80182C',
      accentLight: '#F4DCDE',
      bgTop: '#ECB4BC',
      bgMid: '#FCF0F2',
      bgBottom: '#DCA0AC',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#200408',
      textMid: '#58101C',
      textDim: '#885058',
    },
    dark: {
      scheme: 'dark',
      accent: '#D86070',
      accentLight: 'rgba(216,96,112,0.18)',
      bgTop: '#1A0408',
      bgMid: '#260810',
      bgBottom: '#100408',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F4DCDE',
      textMid: '#B8889A',
      textDim: '#685058',
    },
  },
  {
    id: 'quds-olive',
    name: 'Quds Olive',
    light: {
      scheme: 'light',
      accent: '#3A4818',
      accentLight: '#ECF0D4',
      bgTop: '#D8E4A8',
      bgMid: '#F8FAEC',
      bgBottom: '#C8D898',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#0A140A',
      textMid: '#2A3818',
      textDim: '#788838',
    },
    dark: {
      scheme: 'dark',
      accent: '#98A858',
      accentLight: 'rgba(152,168,88,0.18)',
      bgTop: '#0A100A',
      bgMid: '#14180E',
      bgBottom: '#060A04',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#ECF0D4',
      textMid: '#A0B070',
      textDim: '#586848',
    },
  },
  {
    id: 'ramadan-lantern',
    name: 'Ramadan Lantern',
    light: {
      scheme: 'light',
      accent: '#A06010',
      accentLight: '#FAE8C8',
      bgTop: '#F4CC88',
      bgMid: '#FEF6EC',
      bgBottom: '#ECB870',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#221400',
      textMid: '#5C3808',
      textDim: '#A88848',
    },
    dark: {
      scheme: 'dark',
      accent: '#E8A030',
      accentLight: 'rgba(232,160,48,0.18)',
      bgTop: '#181000',
      bgMid: '#221800',
      bgBottom: '#100C00',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FAE8C8',
      textMid: '#C89858',
      textDim: '#786838',
    },
  },
  {
    id: 'rose-quartz',
    name: 'Rose Quartz',
    light: {
      scheme: 'light',
      accent: '#B8456C',
      accentLight: '#FBE5EC',
      bgTop: '#F7DCE5',
      bgMid: '#FFF5F8',
      bgBottom: '#F4E0E6',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2A101A',
      textMid: '#6E3F50',
      textDim: '#B48A99',
    },
    dark: {
      scheme: 'dark',
      accent: '#EC8AA8',
      accentLight: 'rgba(236,138,168,0.18)',
      bgTop: '#1F0A12',
      bgMid: '#2B1118',
      bgBottom: '#170609',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FBE5EC',
      textMid: '#C9A2AF',
      textDim: '#7C5862',
    },
  },
  {
    id: 'saffron-vale',
    name: 'Saffron Vale',
    light: {
      scheme: 'light',
      accent: '#CC7700',
      accentLight: '#FFF0C8',
      bgTop: '#FFE8A0',
      bgMid: '#FFFDF0',
      bgBottom: '#F8EEB8',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2A1800',
      textMid: '#7A5000',
      textDim: '#C0A050',
    },
    dark: {
      scheme: 'dark',
      accent: '#FFB830',
      accentLight: 'rgba(255,184,48,0.18)',
      bgTop: '#1E1400',
      bgMid: '#2C1E04',
      bgBottom: '#140E00',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FFF5DC',
      textMid: '#CCA850',
      textDim: '#7A6030',
    },
  },
  {
    id: 'sage-bloom',
    name: 'Olive Orchard',
    light: {
      scheme: 'light',
      accent: '#5A7A50',
      accentLight: '#E8F2E4',
      bgTop: '#D4E8CC',
      bgMid: '#F4F9F2',
      bgBottom: '#DCE8D4',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#182010',
      textMid: '#406038',
      textDim: '#88A880',
    },
    dark: {
      scheme: 'dark',
      accent: '#9CD490',
      accentLight: 'rgba(156,212,144,0.18)',
      bgTop: '#0C1608',
      bgMid: '#142010',
      bgBottom: '#080E04',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#E8F2E4',
      textMid: '#A0C898',
      textDim: '#607858',
    },
  },
  {
    id: 'sapphire-dome',
    name: 'Sapphire Dome',
    light: {
      scheme: 'light',
      accent: '#1A3A8A',
      accentLight: '#E0E8F8',
      bgTop: '#C0D4F5',
      bgMid: '#F0F4FC',
      bgBottom: '#CCE0F4',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#081028',
      textMid: '#2A4A7A',
      textDim: '#7890B8',
    },
    dark: {
      scheme: 'dark',
      accent: '#7AA0E8',
      accentLight: 'rgba(122,160,232,0.18)',
      bgTop: '#060E1E',
      bgMid: '#0C1530',
      bgBottom: '#040A14',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#E0E8F8',
      textMid: '#98B0D8',
      textDim: '#5070A0',
    },
  },
  {
    id: 'slate-gate',
    name: 'Sahir Shadow',
    light: {
      scheme: 'light',
      accent: '#4F6070',
      accentLight: '#E6ECF0',
      bgTop: '#D0DCE4',
      bgMid: '#F5F7F9',
      bgBottom: '#D8E2EA',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#141E24',
      textMid: '#3E525E',
      textDim: '#7E909A',
    },
    dark: {
      scheme: 'dark',
      accent: '#94AEC0',
      accentLight: 'rgba(148,174,192,0.18)',
      bgTop: '#0A1018',
      bgMid: '#141C24',
      bgBottom: '#080C10',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#E6ECF0',
      textMid: '#9AAFBD',
      textDim: '#5A6878',
    },
  },
  {
    id: 'storm-veil',
    name: 'Storm Veil',
    light: {
      scheme: 'light',
      accent: '#4A5E7A',
      accentLight: '#E4EAF2',
      bgTop: '#C8D4E0',
      bgMid: '#F4F6F9',
      bgBottom: '#D4DCE8',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#141E2A',
      textMid: '#3E4E62',
      textDim: '#8090A8',
    },
    dark: {
      scheme: 'dark',
      accent: '#8AAAC8',
      accentLight: 'rgba(138,170,200,0.18)',
      bgTop: '#0A0E16',
      bgMid: '#121820',
      bgBottom: '#06080C',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#E4EAF2',
      textMid: '#98AABF',
      textDim: '#5A6A7A',
    },
  },
  {
    id: 'teal-oasis',
    name: 'Teal Oasis',
    light: {
      scheme: 'light',
      accent: '#1A8090',
      accentLight: '#DBEEF4',
      bgTop: '#B0E2EE',
      bgMid: '#EAF8FC',
      bgBottom: '#C0E8EE',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#082430',
      textMid: '#1A6070',
      textDim: '#62AAB8',
    },
    dark: {
      scheme: 'dark',
      accent: '#44C8D8',
      accentLight: 'rgba(68,200,216,0.18)',
      bgTop: '#051418',
      bgMid: '#0A2028',
      bgBottom: '#030C10',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#DBEEF4',
      textMid: '#80C0CA',
      textDim: '#447888',
    },
  },
  {
    id: 'violet-arch',
    name: 'Azim Amethyst',
    light: {
      scheme: 'light',
      accent: '#6040A0',
      accentLight: '#EAE4F6',
      bgTop: '#D8CCEE',
      bgMid: '#F5F2FB',
      bgBottom: '#E2D8F0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1A0E30',
      textMid: '#4E3478',
      textDim: '#9280B0',
    },
    dark: {
      scheme: 'dark',
      accent: '#A880F0',
      accentLight: 'rgba(168,128,240,0.18)',
      bgTop: '#0E081E',
      bgMid: '#180E2C',
      bgBottom: '#090615',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#EAE4F6',
      textMid: '#B098D8',
      textDim: '#685890',
    },
  },
];

export const DEFAULT_THEME_ID = 'sage-garden';

export const getTheme = (id: string): Theme =>
  THEMES.find((t) => t.id === id) ?? THEMES[0];

export const glassCardStyle = (palette: Palette) =>
  ({
    backgroundColor: palette.glassBg,
    borderColor: palette.glassBorder,
    borderWidth: 1,
    borderRadius: 16,
  }) as const;
